name: Automate Gradlew Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Action
        uses: actions/checkout@v4

      - name: Set up JDK 21!
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "adopt"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: latest-dev
          path: build/libs/coffee-0.0.1.jar
